# Reference: https://build-cpp.github.io/cmkr/cmake-toml

[conditions]
test_mode = "ENABLE_TEST"

[project]
name = "UnknownIR"
msvc-runtime = "static"
languages = ["CXX"]
cmake-after = """
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/Output)
add_definitions(-DUNKNOWNIR_SRC_DIR="${CMAKE_CURRENT_SOURCE_DIR}")
"""
test_mode.cmake-after = "add_definitions(-DENABLE_TEST)"

[subdir.test]
condition = "test_mode"


[target.UnknownIR]
type = "library"
include-directories = ["src", "include", "c4core/src"]
headers = ["include/**.h"]
sources = ["src/**.cpp", "src/**.hpp", "src/**.h"]
compile-features = ["cxx_std_20"]

