# Reference: https://build-cpp.github.io/cmkr/cmake-toml

[conditions]
test_mode = "ENABLE_TEST"

[project]
name = "UnknownRebuilder"
msvc-runtime = "static"
languages = ["CXX"]
cmake-after = """
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/Output)
add_definitions(-DUNKNOWN_REBUILDER_SRC_DIR="${CMAKE_CURRENT_SOURCE_DIR}")
"""
test_mode.cmake-after = "add_definitions(-DENABLE_TEST)"


[subdir.test]
condition = "test_mode"
[subdir.3rdparty]
[subdir.tools]


[target.UnknownUtils]
type = "library"
include-directories = ["src/UnknownUtils", "include", "include/UnknownUtils"]
headers = ["include/UnknownUtils/**.h"]
sources = [
    "src/UnknownUtils/**.cpp",
    "src/UnknownUtils/**.hpp",
    "src/UnknownUtils/**.h",
    "src/UnknownUtils/**.inc",
]
compile-features = ["cxx_std_20"]


[target.UnknownIR]
type = "library"
include-directories = ["src/UnknownIR", "include", "include/UnknownIR"]
headers = ["include/UnknownIR/**.h"]
sources = ["src/UnknownIR/**.cpp", "src/UnknownIR/**.hpp", "src/UnknownIR/**.h"]
compile-features = ["cxx_std_20"]
link-libraries = ["UnknownUtils"]


[target.UnknownFrontend]
type = "library"
include-directories = [
    "3rdparty/capstone-retdec/include",
    "src/UnknownFrontend",
    "include",
    "include/UnknownFrontend",
]
headers = ["include/UnknownFrontend/**.h"]
sources = [
    "src/UnknownFrontend/**.cpp",
    "src/UnknownFrontend/**.hpp",
    "src/UnknownFrontend/**.h",
]
compile-features = ["cxx_std_20"]
link-libraries = ["capstone-static", "raw_pdb", "UnknownIR"]


[target.UnknownBackend]
type = "library"
include-directories = [
    "src/UnknownBackend",
    "include",
    "include/UnknownBackend",
]
headers = ["include/UnknownBackend/**.h"]
sources = [
    "src/UnknownBackend/**.cpp",
    "src/UnknownBackend/**.hpp",
    "src/UnknownBackend/**.h",
]
compile-features = ["cxx_std_20"]
link-libraries = ["UnknownMC"]
